name: Create minor release

on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create minor release
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract version from package.json
      id: extract-version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.extract-version.outputs.version }}
        release_name: Release ${{ steps.extract-version.outputs.version }}

    - name: Increment minor version
      id: increment-version
      run: |
        version=${{ steps.extract-version.outputs.version }}
        major=$(echo $version | cut -d '.' -f 1)
        minor=$(echo $version | cut -d '.' -f 2)
        patch=$(echo $version | cut -d '.' -f 3)
        
        minor=$((minor + 1))
        
        new_version="$major.$minor.$patch"
        
        jq --arg new_version "$new_version" '.version = $new_version' package.json > package.json.tmp && mv package.json.tmp package.json
      
    - name: Push incremented version
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@noreply.github.com'
        git commit -am "Increment minor version"
        git push

    - name: Checkout tag
      run: |
        git fetch
        git checkout tags/v${{ steps.extract-version.outputs.version }}

    - name: Create release branch
      run: |
        git checkout -b RELEASE_${{ steps.extract-version.outputs.version }}

    - name: Increment patch version
      id: increment-patch-version
      if: always()
      run: |
        version=${{ steps.extract-version.outputs.version }}
        major=$(echo $version | cut -d '.' -f 1)
        minor=$(echo $version | cut -d '.' -f 2)
        patch=$(echo $version | cut -d '.' -f 3)
        
        patch=$((patch + 1))
        
        new_version="$major.$minor.$patch"
        
        jq --arg new_version "$new_version" '.version = $new_version' package.json > package.json.tmp && mv package.json.tmp package.json
        
    - name: Push incremented patch version
      if: always()
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@noreply.github.com'
        git commit -am "Increment patch version"
        git push origin RELEASE_${{ steps.extract-version.outputs.version }}
