name: Create patch release

on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create patch release
    if: startsWith(github.ref, 'refs/heads/RELEASE_')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract version from .csproj
      id: extract-version
      run: |
        VERSION=$(cat BMW.Portal.Api/BMW.Portal.Api.csproj | grep '<Version>' | sed -E 's/.*<Version>(.*)<\/Version>.*/\1/')
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.extract-version.outputs.version }}
        release_name: Release ${{ steps.extract-version.outputs.version }}

    - name: Increment patch version
      id: increment-patch-version
      run: |
        version=${{ steps.extract-version.outputs.version }}
        major=$(echo $version | cut -d '.' -f 1)
        minor=$(echo $version | cut -d '.' -f 2)
        patch=$(echo $version | cut -d '.' -f 3)
        
        patch=$((patch + 1))
        
        new_version="$major.$minor.$patch"
        
        sed -i "s/<Version>.*<\/Version>/<Version>$new_version<\/Version>/" BMW.Portal.Api/BMW.Portal.Api.csproj
          
    - name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch     
  
    - name: Push incremented patch version
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@noreply.github.com'
        git commit -am "Increment patch version"
        git push origin ${{ steps.extract_branch.outputs.branch }}
  
    - name: Checkout tag
      run: |
        git fetch
        git checkout tags/v${{ steps.extract-version.outputs.version }}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        sleep 30