name: Prepare release

on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Prepare release
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
        aws-region: ap-northeast-1

    - name: Extract version from .csproj
      id: extract-version
      run: |
        VERSION=$(cat BMW.Portal.Api/BMW.Portal.Api.csproj | grep '<Version>' | sed -E 's/.*<Version>(.*)<\/Version>.*/\1/')
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.extract-version.outputs.version }}
        release_name: Release ${{ steps.extract-version.outputs.version }}

    - name: Create release branch
      run: |
        git checkout -b RELEASE_${{ steps.extract-version.outputs.version }}

    - name: Increment patch version
      id: increment-patch-version
      run: |
        version=${{ steps.extract-version.outputs.version }}
        major=$(echo $version | cut -d '.' -f 1)
        minor=$(echo $version | cut -d '.' -f 2)
        patch=$(echo $version | cut -d '.' -f 3)
        
        patch=$((minor + 1))
        
        new_version="$major.$minor.$patch"
        
        sed -i "s/<Version>.*<\/Version>/<Version>$new_version<\/Version>/" BMW.Portal.Api/BMW.Portal.Api.csproj
        
    - name: Push incremented patch version
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@noreply.github.com'
        git commit -am "Increment patch version"
        git push
        git checkout master

    - name: Increment minor version
      id: increment-version
      run: |
        version=${{ steps.extract-version.outputs.version }}
        major=$(echo $version | cut -d '.' -f 1)
        minor=$(echo $version | cut -d '.' -f 2)
        patch=$(echo $version | cut -d '.' -f 3)
        
        minor=$((minor + 1))
        
        new_version="$major.$minor.$patch"
        
        sed -i "s/<Version>.*<\/Version>/<Version>$new_version<\/Version>/" BMW.Portal.Api/BMW.Portal.Api.csproj
      
    - name: Push incremented version
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@noreply.github.com'
        git commit -am "Increment minor version"
        git push