name: TESTING

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
      
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
#    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    env: 
      VARIABLE: ${{ github.event_name == 'push' && 'staging' || inputs.environment }}

    steps:
    - name: Echo
      run: |
        echo "It is running and $VARIABLE"
        echo ${{ github.event_name }}
